name: Docker Image CI

on:
  schedule:
    - cron: "0 0 * * *"   # Every day at midnight
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag trac:stable
